version: "3"
services:
  gin-api:
    build: .
    container_name: hakus_gin_api
    volumes:
      - $HOME/.aws:/root/.aws
      - ./:/go/src/
    ports:
      - "9601:8080"
    tty: true
    stdin_open: true
    depends_on:
      - rest-db
    env_file:
      - .env
    links:
      - rest-db
  rest-db:
    image: mysql:8.0
    container_name: hakus_gin_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: karo
      TZ: 'Asia/Tokyo'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 9602:3306
    tty: true
    volumes:
      - rest-db:/var/lib/mysql
  dynamo-db:
    image: amazon/dynamodb-local
    ports:
      - 9603:8000
    volumes:
      - dynamo-db:/home/dynamodblocal
volumes:
  rest-db:
  dynamo-db:
    driver: local
